import { type Tower } from "../../types";

// TODO: add stats
export const uranium_stryker: Tower = [
  {
    damage: 40,
    cooldown: 21,
    exclusion: 160,
    radius: 50,
    inaccuracy: 40,
    rad_strength: 0.8,
    rad_length: 8,
    rupture: 0.35,
    rupture_duration: 7,
    shield_bypass: 0.3,
    armor_piercing: true,
    camo: true,
    // already placed so dont have idea for price.
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {
    //idk about the path on this one either
    // he still doesnt scroll down
    damage: 2_500,
    cooldown: 11.9,
    exclusion: 60,
    radius: 70,
    inaccuracy: 15,
    rad_strength: 2.4,
    rad_length: 11,
    rupture: 0.5,
  },
];
export const mechanic: Tower = [
  {
    spawns_damage: 5,
    crit_chance: 0.2,
    crit_dmg: 5,
    cooldown: 5,
    spawns_cd: 1.2,
    range: 30,
    spawns_range: 110,
    max_spawns: 3,
    damage_buff: 0.08,
    cooldown_buff: 0.064,
    aim: 100,
    shield_dmg: 0.75,
    price: 2_625,
  },
  {
    spawns_damage: 5,
    crit_chance: 0.23,
    crit_dmg: 6,
    cooldown: 4.5,
    spawns_cd: 1.2,
    range: 30,
    spawns_range: 120,
    max_spawns: 3,
    damage_buff: 0.12,
    cooldown_buff: 0.064,
    aim: 100,
    shield_dmg: 0.75,
    price: 1_700,
  },
  {
    spawns_damage: 12,
    crit_chance: 0.26,
    crit_dmg: 6,
    cooldown: 4,
    spawns_cd: 1.2,
    range: 30,
    spawns_range: 130,
    max_spawns: 4,
    damage_buff: 0.12,
    cooldown_buff: 0.096,
    camo: true,
    aim: 100,
    shield_dmg: 0.75,
    price: 4_350,
  },
  {
    spawns_damage: 40,
    crit_chance: 0.26,
    crit_dmg: 7.25,
    cooldown: 3.5,
    spawns_cd: 0.96,
    range: 30,
    spawns_range: 130,
    max_spawns: 4,
    damage_buff: 0.16,
    cooldown_buff: 0.096,
    armor_piercing: true,
    camo: true,
    aim: 100,
    shield_dmg: 0.75,
    price: 21_700,
  },
  {
    spawns_damage: 100,
    crit_chance: 0.3,
    crit_dmg: 7.25,
    cooldown: 3.5,
    spawns_cd: 0.8,
    range: 30,
    spawns_range: 140,
    max_spawns: 4,
    execution: 0.45,
    damage_buff: 0.16,
    cooldown_buff: 0.128,
    armor_piercing: true,
    camo: true,
    aim: 100,
    shield_dmg: 0.75,
    price: 97_300,
  },
  {
    spawns_damage: 300,
    crit_chance: 0.3,
    crit_dmg: 9,
    cooldown: 3,
    spawns_cd: 0.8,
    range: 30,
    spawns_range: 160,
    max_spawns: 5,
    execution: 0.45,
    damage_buff: 0.24,
    cooldown_buff: 0.192,
    armor_piercing: true,
    camo: true,
    aim: 100,
    shield_dmg: 0.75,
    price: 460_300,
  },
  {
    spawns_damage: 200_000,
    crit_chance: 1,
    crit_dmg: 9,
    cooldown: 3,
    spawns_cd: 0.1,
    range: 30,
    spawns_range: 220,
    max_spawns: 5,
    execution: 16,
    damage_buff: 0.24,
    cooldown_buff: 0.4,
    armor_piercing: true,
    camo: true,
    aim: 100,
    shield_dmg: 0.75,
    price: 5_022_000,
  },
  {
    spawns_damage: 80_000,
    crit_chance: 0.3,
    crit_dmg: 120,
    cooldown: 3,
    spawns_cd: 1,
    range: 30,
    armor_destruction: 0.2,
    spawns_range: 160,
    max_spawns: 20,
    execution: 0.45,
    damage_buff: 0.5,
    cooldown_buff: 0.192,
    armor_piercing: true,
    camo: true,
    aim: 100,
    shield_dmg: 0.75,
    price: 5_704_000,
  },
];
// TODO: add stats
export const mystic_zero_two: Tower = [
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    damage: 10_000,
    cooldown: 0.09,
    range: 270,
    bleed: 10_000,
    hollow_point: 50,
    execution: 27,
    camo: true,
    aim: 120,
    shield_dmg: 0.9,
  },
];
