// TODO: Recheck stats
import { TowerRarity, TowerType, type Tower } from "../types";

export const adamant_stryker: Tower = {
  id: "adamant_stryker",
  variantOf: "stryker",
  name: "Adamant Stryker",
  rarity: TowerRarity.Exalted,
  type: [TowerType.Support, TowerType.UNKNOWN_TYPE],
  levels: [
    {
      level: 1,
      price: 9400,
      stats: {
        damage: 60,
        cooldown: 0.25,
        exclusion: 120,
        radius: 45,
        inaccuracy: 90,
        burst: 3,
        burst_cd: 15,
        rad_strength: 0.3,
        rad_length: 3,
        camo: true,
      },
    },
    {
      level: 2,
      price: 4600,
      stats: {
        damage: 60,
        cooldown: 0.25,
        exclusion: 110,
        radius: 45,
        inaccuracy: 80,
        burst: 3,
        burst_cd: 14,
        rad_strength: 0.3,
        rad_length: 3,
        camo: true,
      },
    },
    {
      level: 3,
      price: 10200,
      stats: {
        damage: 125,
        cooldown: 0.25,
        exclusion: 110,
        radius: 50,
        inaccuracy: 80,
        burst: 3,
        burst_cd: 14,
        rad_strength: 0.3,
        rad_length: 4,
        camo: true,
      },
    },
    {
      level: 4,
      price: 42900,
      stats: {
        damage: 220,
        cooldown: 0.25,
        exclusion: 100,
        radius: 50,
        inaccuracy: 70,
        burst: 4,
        burst_cd: 12.5,
        rad_strength: 0.325,
        rad_length: 4,
        camo: true,
      },
    },
    {
      level: 5,
      price: 148000,
      stats: {
        damage: 550,
        cooldown: 0.25,
        exclusion: 100,
        radius: 55,
        inaccuracy: 60,
        burst: 4,
        burst_cd: 12.5,
        rad_strength: 0.325,
        rad_length: 5,
        camo: true,
      },
    },
    {
      level: 6,
      price: 453000,
      stats: {
        damage: 1225,
        cooldown: 0.2,
        exclusion: 100,
        radius: 55,
        inaccuracy: 60,
        burst: 5,
        burst_cd: 11,
        rad_strength: 0.35,
        rad_length: 5,
        camo: true,
      },
    },
  ],
  paths: [
    {
      id: "a",
      level: 7,
      price: 5240000,
      stats: {
        damage: 4750,
        cooldown: 0.35,
        exclusion: 100,
        radius: 65,
        inaccuracy: 60,
        burst: 7,
        burst_cd: 11,
        rad_strength: 0.35,
        rad_length: 6.25,
        camo: true,
      },
    },
    {
      id: "b",
      level: 7,
      price: 6830000,
      stats: {
        damage: 3625,
        cooldown: 0.2,
        exclusion: 85,
        radius: 55,
        inaccuracy: 35,
        burst: 5,
        burst_cd: 7.5,
        rad_strength: 0.525,
        rad_length: 5,
        camo: true,
      },
    },
  ],
};
