// TODO: Recheck stats
import { TowerRarity, TowerType, type Tower } from "../types";

export const apollos_blessing: Tower = {
  id: "apollos_blessing",
  name: "Apollo's Blessing",
  rarity: TowerRarity.Exalted,
  variantOf: "shrine_of_apollo",
  type: [TowerType.Offense],
  levels: [
    {
      level: 1,
      price: 12300,
      stats: {
        damage: 12,
        beams: 2,
        cooldown: 0.5,
        radius: 6,
        rad_strength: 0.05,
        rad_length: 3,
        valor: 0.2,
        armor_piercing: true,
        camo: true,
        shield_dmg: 0.03,
      },
    },
    {
      level: 2,
      price: 7_750,
      stats: {
        damage: 16,
        beams: 2,
        cooldown: 0.5,
        radius: 6,
        rad_strength: 0.07,
        rad_length: 4,
        valor: 0.25,
        armor_piercing: true,
        camo: true,
        shield_dmg: 0.03,
      },
    },
    {
      level: 3,
      price: 18_550,
      stats: {
        damage: 40,
        beams: 3,
        cooldown: 0.5,
        radius: 7,
        rad_strength: 0.09,
        rad_length: 4,
        valor: 0.25,
        armor_piercing: true,
        camo: true,
        shield_dmg: 0.03,
      },
    },
    {
      level: 4,
      price: 82_400,
      stats: {
        damage: 120,
        beams: 3,
        cooldown: 0.5,
        radius: 9,
        rad_strength: 0.09,
        rad_length: 5,
        valor: 0.35,
        armor_piercing: true,
        camo: true,
        shield_dmg: 0.03,
      },
    },
    {
      level: 5,
      price: 252_000,
      stats: {
        damage: 300,
        beams: 4,
        cooldown: 0.5,
        radius: 12,
        rad_strength: 0.12,
        rad_length: 5,
        valor: 0.35,
        armor_piercing: true,
        camo: true,
        shield_dmg: 0.03,
      },
    },
    {
      level: 6,
      price: 963_000,
      stats: {
        damage: 900,
        beams: 5,
        cooldown: 0.4,
        radius: 12,
        rad_strength: 0.12,
        rad_length: 6.5,
        valor: 0.5,
        armor_piercing: true,
        camo: true,
        shield_dmg: 0.03,
      },
    },
  ],
  paths: [
    {
      id: "a",
      level: 7,
      price: 11_420_000,
      stats: {
        damage: 3600,
        beams: 5,
        cooldown: 0.4,
        radius: 20,
        rad_strength: 0.24,
        rad_length: 6.5,
        valor: 0.5,
        armor_piercing: true,
        camo: true,
        shield_dmg: 0.03,
      },
    },
    {
      id: "b",
      level: 7,
      price: 14_850_000,
      stats: {
        damage: 2300,
        beams: 7,
        cooldown: 0.35,
        radius: 12,
        rad_strength: 0.12,
        rad_length: 10,
        valor: 2.25,
        armor_piercing: true,
        camo: true,
        shield_dmg: 0.03,
      },
    },
  ],
};
