//TODO: Recheck stats
import { TowerRarity, TowerType, type Tower } from "../types";

export const casual_zero_two: Tower = {
  id: "casual_zero_two",
  name: "Casual Zero Two",
  rarity: TowerRarity.Exalted,
  type: [TowerType.Offense],
  variantOf: "zero_two",
  levels: [
    {
      level: 1,
      price: 5100,
      stats: {
        damage: 2,
        cooldown: 0.18,
        range: 65,
        bleed: 1,
        boss_slayer: 1.3,
        hollow_point: 1.5,
        execution: 2.4,
        shield_dmg: 0.3,
      },
    },
    {
      level: 2,
      price: 2280,
      stats: {
        damage: 3,
        cooldown: 0.18,
        range: 75,
        bleed: 2,
        boss_slayer: 1.4,
        hollow_point: 2,
        execution: 2.4,
        shield_dmg: 0.3,
      },
    },
    {
      level: 3,
      price: 6165,
      stats: {
        damage: 6,
        cooldown: 0.18,
        range: 80,
        bleed: 3,
        boss_slayer: 1.4,
        hollow_point: 2,
        execution: 3,
        shield_dmg: 0.3,
      },
    },
    {
      level: 4,
      price: 29080,
      stats: {
        damage: 15,
        cooldown: 0.18,
        range: 80,
        bleed: 6,
        boss_slayer: 1.55,
        hollow_point: 3.5,
        execution: 3,
        shield_dmg: 0.3,
      },
    },
    {
      level: 5,
      price: 105190,
      stats: {
        damage: 40,
        cooldown: 0.15,
        range: 95,
        bleed: 13,
        boss_slayer: 1.8,
        hollow_point: 3.5,
        execution: 3.8,
        shield_dmg: 0.3,
      },
    },
    {
      level: 6,
      price: 393960,
      stats: {
        damage: 100,
        cooldown: 0.15,
        range: 110,
        bleed: 30,
        boss_slayer: 1.8,
        hollow_point: 3.5,
        execution: 5.4,
        shield_dmg: 0.3,
        camo: true,
      },
    },
  ],
  paths: [
    {
      id: "a",
      level: 7,
      price: 2682685,
      stats: {
        damage: 750,
        cooldown: 0.15,
        range: 110,
        bleed: 90,
        boss_slayer: 2.4,
        hollow_point: 3.5,
        execution: 60,
        shield_dmg: 0.3,
        camo: true,
      },
    },
    {
      id: "b",
      level: 7,
      price: 4022685,
      stats: {
        damage: 750,
        cooldown: 0.09,
        range: 135,
        bleed: 200,
        boss_slayer: 2.5,
        hollow_point: 5,
        execution: 5.4,
        shield_dmg: 0.3,
        camo: true,
      },
    },
  ],
};
