import { Tower, TowerRarity, TowerType } from "../types";

export const elder_godfather: Tower = {
  id: "elder_godfather",
  name: "Elder Godfather",
  rarity: TowerRarity.Unknown,
  type: [TowerType.Offense],
  levels: [
    {
      level: 1,
      price: 4_200,
      stats: {
        damage: 5,
        cooldown: 0.18,
        range: 90,
        radius: 1,
        bleed: 1,
        shield_dmg: 1,
      },
    },
    {
      level: 2,
      price: 1_650,
      stats: {
        damage: 5,
        cooldown: 0.18,
        range: 105,
        radius: 1,
        bleed: 1,
        camo: true,
        shield_dmg: 1,
      },
    },
    {
      level: 3,
      price: 4_600,
      stats: {
        damage: 8,
        cooldown: 0.18,
        range: 120,
        radius: 2,
        bleed: 2,
        camo: true,
        armor_piercing: true,
        shield_dmg: 1,
      },
    },
    {
      level: 4,
      price: 14_200,
      stats: {
        damage: 20,
        cooldown: 0.135,
        range: 120,
        radius: 2,
        bleed: 4,
        camo: true,
        armor_piercing: true,
        shield_dmg: 1,
      },
    },
    {
      level: 5,
      price: 52_000,
      stats: {
        damage: 40,
        cooldown: 0.105,
        range: 120,
        radius: 2,
        bleed: 8,
        camo: true,
        armor_piercing: true,
        shield_dmg: 1,
      },
    },
    {
      level: 6,
      price: 186_000,
      stats: {
        damage: 120,
        cooldown: 0.105,
        range: 135,
        radius: 3,
        bleed: 15,
        camo: true,
        armor_piercing: true,
        shield_dmg: 1,
      },
    },
  ],
  paths: [
    {
      id: "a",
      level: 7,
      price: 2_640_000,
      stats: {
        damage: 900,
        cooldown: 0.05,
        range: 135,
        radius: 5,
        bleed: 25,
        camo: true,
        armor_piercing: true,
        shield_dmg: 1,
      },
    },
    {
      id: "b",
      level: 7,
      price: 3_060_000,
      stats: {
        damage: 3_000,
        cooldown: 0.105,
        range: 220,
        radius: 3,
        bleed: 45,
        execution: 1,
        camo: true,
        armor_piercing: true,
        shield_dmg: 1,
      },
    },
  ],
};
