// TODO: Recheck stats
import { TowerRarity, TowerType, type Tower } from "../types";

export const high_engineer: Tower = {
  id: "high_engineer",
  name: "High Engineer",
  rarity: TowerRarity.Exalted,
  variantOf: "engineer",
  type: [TowerType.Defense],
  levels: [
    {
      level: 1,
      price: 2_350,
      stats: {
        spawns_damage: 6,
        cooldown: 20,
        spawns_cd: 0.6,
        range: 30,
        spawns_range: 60,
        valor: 0.3,
        max_spawns: 3,
        damage_buff: 0.0625,
        cooldown_buff: 0.05,
        shield_dmg: 0.75,
      },
    },
    {
      level: 2,
      price: 1_525,
      stats: {
        spawns_damage: 6,
        cooldown: 19,
        spawns_cd: 0.6,
        range: 30,
        spawns_range: 65,
        valor: 0.3,
        max_spawns: 4,
        damage_buff: 0.09375,
        cooldown_buff: 0.05,
        shield_dmg: 0.75,
      },
    },
    {
      level: 3,
      price: 3_875,
      stats: {
        spawns_damage: 15,
        cooldown: 18,
        spawns_cd: 0.6,
        range: 30,
        spawns_range: 70,
        valor: 0.45,
        max_spawns: 4,
        damage_buff: 0.09375,
        cooldown_buff: 0.075,
        camo: true,
        shield_dmg: 0.75,
      },
    },
    {
      level: 4,
      price: 19_400,
      stats: {
        spawns_damage: 55,
        cooldown: 17,
        spawns_cd: 0.45,
        range: 30,
        spawns_range: 70,
        valor: 0.45,
        max_spawns: 4,
        armor_destruction: 0.08,
        damage_buff: 0.125,
        cooldown_buff: 0.075,
        camo: true,
        shield_dmg: 0.75,
      },
    },
    {
      level: 5,
      price: 87_000,
      stats: {
        spawns_damage: 170,
        cooldown: 17,
        spawns_cd: 0.45,
        range: 30,
        spawns_range: 85,
        valor: 0.7,
        max_spawns: 4,
        armor_destruction: 0.15,
        damage_buff: 0.125,
        cooldown_buff: 0.1,
        camo: true,
        shield_dmg: 0.75,
      },
    },
    {
      level: 6,
      price: 411_500,
      stats: {
        spawns_damage: 300,
        cooldown: 15,
        spawns_cd: 0.225,
        range: 30,
        spawns_range: 100,
        valor: 0.7,
        max_spawns: 5,
        armor_destruction: 0.15,
        damage_buff: 0.1875,
        cooldown_buff: 0.15,
        camo: true,
        shield_dmg: 0.75,
      },
    },
  ],
  paths: [
    {
      id: "a",
      level: 7,
      price: 4_487_500,
      stats: {
        spawns_damage: 2400,
        cooldown: 15,
        spawns_cd: 0.165,
        range: 30,
        spawns_range: 100,
        valor: 3.5,
        max_spawns: 5,
        armor_destruction: 0.15,
        damage_buff: 0.1875,
        cooldown_buff: 0.225,
        camo: true,
        shield_dmg: 0.75,
      },
    },
    {
      id: "b",
      level: 7,
      price: 5_097_000,
      stats: {
        spawns_damage: 8000,
        cooldown: 10,
        spawns_cd: 0.45,
        range: 30,
        spawns_range: 145,
        valor: 0.7,
        max_spawns: 7,
        armor_destruction: 0.4,
        damage_buff: 0.28125,
        cooldown_buff: 0.15,
        camo: true,
        shield_dmg: 0.75,
      },
    },
  ],
};
