// TODO: Add ability iirc
import { TowerRarity, TowerType, type Tower } from "../types";

export const huge_heckerman: Tower = {
  id: "huge_heckerman",
  name: "HUGE Heckerman",
  rarity: TowerRarity.Synthesized,
  type: [TowerType.Offense],
  levels: [
    {
      level: 1,
      price: 355350,
      stats: {
        damage: 250,
        cooldown: 1,
        range: 690,
        radius: 690,
        shield_bypass: 0.69,
        camo: true,
        shield_dmg: 69,
      },
    },
    {
      level: 2,
      price: 93150,
      stats: {
        damage: 500,
        cooldown: 1,
        range: 690,
        radius: 690,
        shield_bypass: 0.69,
        camo: true,
        shield_dmg: 69,
      },
    },
    {
      level: 3,
      price: 248400,
      stats: {
        damage: 750,
        cooldown: 0.8,
        range: 690,
        radius: 690,
        shield_bypass: 0.69,
        camo: true,
        shield_dmg: 69,
      },
    },
    {
      level: 4,
      price: 1069500,
      stats: {
        damage: 1500,
        cooldown: 0.65,
        range: 690,
        radius: 690,
        shield_bypass: 0.69,
        camo: true,
        shield_dmg: 69,
      },
    },
    {
      level: 5,
      price: 4643700,
      stats: {
        damage: 4500,
        cooldown: 0.55,
        range: 690,
        radius: 690,
        shield_bypass: 0.69,
        camo: true,
        armor_piercing: true,
        shield_dmg: 69,
      },
    },
    {
      level: 6,
      price: 20148000,
      stats: {
        damage: 12500,
        cooldown: 0.3,
        range: 690,
        radius: 690,
        shield_bypass: 0.69,
        camo: true,
        armor_piercing: true,
        shield_dmg: 69,
      },
    },
  ],
  paths: [
    {
      id: "a",
      level: 7,
      price: 268582500,
      stats: {
        damage: 150000,
        cooldown: 0.3,
        range: 690,
        radius: 690,
        shield_bypass: 0.69,
        camo: true,
        armor_piercing: true,
        shield_dmg: 69,
      },
    },
    {
      id: "b",
      level: 7,
      price: 295458000,
      stats: {
        damage: 25000,
        cooldown: 0.08,
        range: 690,
        radius: 690,
        shield_bypass: 0.69,
        execution: 1.75,
        camo: true,
        armor_piercing: true,
        shield_dmg: 69,
      },
    },
  ],
};
