// TODO: Find rarity, recheck stats
import { TowerRarity, TowerType, type Tower } from "../types";

export const huge_elder_godfather: Tower = {
  id: "huge_elder_godfather",
  name: "HUGE Elder Godfather",
  rarity: TowerRarity.Unknown,
  type: [TowerType.Offense],
  levels: [
    {
      level: 1,
      price: 42000,
      stats: {
        damage: 50,
        cooldown: 0.18,
        range: 180,
        radius: 1,
        bleed: 5,
        shield_dmg: 0.2,
      },
    },
    {
      level: 2,
      price: 16500,
      stats: {
        damage: 50,
        cooldown: 0.18,
        range: 210,
        radius: 1,
        bleed: 5,
        camo: true,
        shield_dmg: 0.2,
      },
    },
    {
      level: 3,
      price: 46000,
      stats: {
        damage: 80,
        cooldown: 0.18,
        range: 240,
        radius: 2,
        bleed: 10,
        camo: true,
        armor_piercing: true,
        shield_dmg: 0.2,
      },
    },
    {
      level: 4,
      price: 142000,
      stats: {
        damage: 200,
        cooldown: 0.135,
        range: 240,
        radius: 2,
        bleed: 20,
        camo: true,
        armor_piercing: true,
        shield_dmg: 0.2,
      },
    },
    {
      level: 5,
      price: 520000,
      stats: {
        damage: 400,
        cooldown: 0.105,
        range: 240,
        radius: 2,
        bleed: 40,
        camo: true,
        armor_piercing: true,
        shield_dmg: 0.2,
      },
    },
    {
      level: 6,
      price: 1860000,
      stats: {
        damage: 1200,
        cooldown: 0.105,
        range: 270,
        radius: 3,
        bleed: 75,
        camo: true,
        armor_piercing: true,
        shield_dmg: 0.2,
      },
    },
  ],
  paths: [
    {
      id: "a",
      level: 7,
      price: 26400000,
      stats: {
        damage: 9000,
        cooldown: 0.5,
        range: 270,
        radius: 5,
        bleed: 125,
        camo: true,
        armor_piercing: true,
        shield_dmg: 0.2,
      },
    },
    {
      id: "b",
      level: 7,
      price: 30600000,
      stats: {
        damage: 30000,
        cooldown: 0.105,
        range: 440,
        radius: 3,
        bleed: 225,
        execution: 1,
        camo: true,
        armor_piercing: true,
        shield_dmg: 0.2,
      },
    },
  ],
};
