// TODO: Check type
import { TowerRarity, TowerType, type Tower } from "../types";

export const huge_zero_two_school: Tower = {
  id: "huge_zero_two_school",
  name: "HUGE Zero Two (School)",
  rarity: TowerRarity.Synthesized,
  variantOf: "zero_two",
  type: [TowerType.Offense],
  levels: [
    {
      level: 1,
      price: 7980,
      stats: {
        damage: 100,
        cooldown: 0.18,
        range: 95,
        bleed: 150,
        hollow_point: 4.5,
        execution: 1.8,
        shield_dmg: 0.3,
        instabreak: 0.004,
      },
    },
    {
      level: 2,
      price: 3570,
      stats: {
        damage: 150,
        cooldown: 0.18,
        range: 115,
        bleed: 250,
        hollow_point: 6,
        execution: 1.8,
        shield_dmg: 0.3,
        instabreak: 0.0044,
      },
    },
    {
      level: 3,
      price: 9660,
      stats: {
        damage: 300,
        cooldown: 0.18,
        range: 120,
        bleed: 400,
        hollow_point: 6,
        execution: 2.25,
        shield_dmg: 0.3,
        instabreak: 0.0048,
      },
    },
    {
      level: 4,
      price: 45570,
      stats: {
        damage: 750,
        cooldown: 0.18,
        range: 120,
        bleed: 750,
        hollow_point: 10.5,
        execution: 2.25,
        shield_dmg: 0.3,
        instabreak: 0.0052,
      },
    },
    {
      level: 5,
      price: 164850,
      stats: {
        damage: 2000,
        cooldown: 0.15,
        range: 145,
        bleed: 1650,
        hollow_point: 10.5,
        execution: 2.85,
        shield_dmg: 0.3,
        instabreak: 0.0056,
      },
    },
    {
      level: 6,
      price: 617400,
      stats: {
        damage: 5000,
        cooldown: 0.15,
        range: 165,
        bleed: 3750,
        hollow_point: 10.5,
        execution: 4.05,
        camo: true,
        shield_dmg: 0.3,
        instabreak: 0.006,
      },
    },
  ],
  paths: [
    {
      id: "a",
      level: 7,
      price: 4204203,
      stats: {
        damage: 37500,
        cooldown: 0.15,
        range: 165,
        bleed: 11250,
        hollow_point: 10.5,
        execution: 15,
        camo: true,
        shield_dmg: 0.3,
        instabreak: 0.009,
      },
    },
    {
      id: "b",
      level: 7,
      price: 6304203,
      stats: {
        damage: 5000,
        cooldown: 0.09,
        range: 200,
        bleed: 25000,
        hollow_point: 15,
        execution: 4.05,
        camo: true,
        shield_dmg: 0.3,
        instabreak: 0.1,
      },
    },
  ],
};
