// TODO: Fix l6 {price}
import { TowerRarity, TowerType, type Tower } from "../types";

export const killzone: Tower = {
  id: "killzone",
  name: "Killzone",
  variantOf: "killzone",
  rarity: TowerRarity.Prestigious,
  type: [TowerType.Offense, TowerType.Support],
  levels: [
    {
      level: 1,
      price: 4700,
      stats: {
        damage: 200,
        crit_chance: 0.06,
        crit_dmg: 1.4,
        cooldown: 9,
        exclusion: 200,
        targeting_rate: 0.09,
        radius: 6,
        rupture: 0.3,
        rupture_duration: 3,
        armor_piercing: true,
        shield_dmg: 25,
      },
    },
    {
      level: 2,
      price: 4300,
      stats: {
        damage: 350,
        crit_chance: 0.08,
        crit_dmg: 1.6,
        cooldown: 9,
        exclusion: 200,
        targeting_rate: 0.1,
        radius: 6,
        rupture: 0.3,
        rupture_duration: 4,
        armor_piercing: true,
        shield_dmg: 35,
      },
    },
    {
      level: 3,
      price: 22100,
      stats: {
        damage: 1450,
        crit_chance: 0.08,
        crit_dmg: 1.9,
        cooldown: 8.1,
        exclusion: 200,
        targeting_rate: 0.1,
        radius: 7,
        rupture: 0.4,
        rupture_duration: 4.5,
        armor_piercing: true,
        shield_dmg: 35,
      },
    },
    {
      level: 4,
      price: 104000,
      stats: {
        damage: 6000,
        crit_chance: 0.1,
        crit_dmg: 2.3,
        cooldown: 8.1,
        exclusion: 200,
        targeting_rate: 0.12,
        radius: 8,
        rupture: 0.4,
        rupture_duration: 4.5,
        camo: true,
        armor_piercing: true,
        shield_dmg: 50,
      },
    },
    {
      level: 5,
      price: 488800,
      stats: {
        damage: 22500,
        crit_chance: 0.13,
        crit_dmg: 2.8,
        cooldown: 7.2,
        exclusion: 200,
        targeting_rate: 0.12,
        radius: 8,
        rupture: 0.55,
        rupture_duration: 5.5,
        camo: true,
        armor_piercing: true,
        shield_dmg: 50,
      },
    },
    {
      level: 6,
      price: 488800,
      stats: {
        damage: 84000,
        crit_chance: 0.13,
        crit_dmg: 3.4,
        cooldown: 6.3,
        exclusion: 200,
        targeting_rate: 0.14,
        radius: 10,
        rupture: 0.55,
        rupture_duration: 7,
        camo: true,
        armor_piercing: true,
        shield_dmg: 70,
      },
    },
  ],
  paths: [
    {
      id: "a",
      level: 7,
      price: 33770000,
      stats: {
        damage: 540000,
        crit_chance: 0.13,
        crit_dmg: 3.4,
        cooldown: 6.3,
        exclusion: 200,
        targeting_rate: 0.14,
        radius: 14,
        rupture: 0.7,
        rupture_duration: 10.5,
        camo: true,
        armor_piercing: true,
        shield_dmg: 150,
      },
    },
    {
      id: "b",
      level: 7,
      price: 40666000,
      stats: {
        damage: 770000,
        crit_chance: 0.18,
        crit_dmg: 4,
        cooldown: 4.5,
        exclusion: 200,
        targeting_rate: 0.21,
        radius: 4,
        rupture: 0.55,
        rupture_duration: 7,
        camo: true,
        armor_piercing: true,
        shield_dmg: 70,
      },
    },
  ],
};
