import { TowerRarity, TowerType, type Tower, GeneratorType } from "../types";

export const lemonade_stand: Tower = {
  id: "lemonade_stand",
  name: "Lemonade Stand",
  rarity: TowerRarity.Elusive,
  generatorType: GeneratorType.Time,
  type: [TowerType.Generator, TowerType.Support],
  variantOf: "lemonade_stand",
  levels: [
    {
      level: 1,
      price: 1_725,
      stats: {
        income: 15,
        cooldown: 4,
        range: 45,
        bounty_amp: 0.1,
        bounty_add: 1,
        cooldown_buff: 0.05,
      },
    },
    {
      level: 2,
      price: 900,
      stats: {
        income: 25,
        cooldown: 4,
        range: 50,
        bounty_amp: 0.12,
        bounty_add: 2,
        cooldown_buff: 0.05,
      },
    },
    {
      level: 3,
      price: 1_950,
      stats: {
        income: 40,
        cooldown: 3.5,
        range: 50,
        bounty_amp: 0.15,
        bounty_add: 4,
        cooldown_buff: 0.075,
      },
    },
    {
      level: 4,
      price: 6_500,
      stats: {
        income: 100,
        cooldown: 3.5,
        range: 60,
        bounty_amp: 0.15,
        bounty_add: 10,
        damage_buff: 0.1,
        cooldown_buff: 0.075,
      },
    },
    {
      level: 5,
      price: 21_600,
      stats: {
        income: 250,
        cooldown: 3,
        range: 60,
        bounty_amp: 0.2,
        bounty_add: 25,
        damage_buff: 0.15,
        cooldown_buff: 0.075,
      },
    },
    {
      level: 6,
      price: 72_000,
      stats: {
        income: 600,
        cooldown: 3,
        range: 70,
        bounty_amp: 0.2,
        bounty_add: 65,
        damage_buff: 0.15,
        cooldown_buff: 0.1,
      },
    },
  ],
  paths: [
    {
      id: "a",
      level: 7,
      price: 777_000,
      stats: {
        income: 3250,
        cooldown: 1.5,
        range: 95,
        bounty_amp: 0.32,
        bounty_add: 750,
        interest: 0.02,
        damage_buff: 0.15,
        cooldown_buff: 0.1,
      },
    },
    {
      id: "b",
      level: 7,
      price: 888_000,
      stats: {
        income: 8000,
        cooldown: 3,
        range: 75,
        bounty_amp: 0.2,
        bounty_add: 65,
        damage_buff: 0.25,
        cooldown_buff: 0.175,
      },
    },
  ],
};
