// TODO: Check ability
import { TowerRarity, TowerType, type Tower } from "../types";

export const phase_turret: Tower = {
  id: "phase_turret",
  name: "Phase Turret",
  rarity: TowerRarity.Legendary,
  type: [TowerType.Offense],
  variantOf: "turret",
  levels: [
    {
      level: 1,
      price: 16900,
      stats: {
        damage: 27,
        crit_chance: 0.08,
        crit_dmg: 90,
        cooldown: 0.4,
        range: 150,
        targeting_rate: 0.5,
        radius: 6,
        burst: 8,
        burst_cd: 2.4,
        bleed: 2,
        armor_destruction: 0.03,
        shield_bypass: 0.65,
        camo: true,
      },
    },
    {
      level: 2,
      price: 11500,
      stats: {
        damage: 38,
        crit_chance: 0.1,
        crit_dmg: 103.5,
        cooldown: 0.375,
        range: 180,
        targeting_rate: 0.5,
        radius: 6,
        burst: 10,
        burst_cd: 2.4,
        bleed: 2,
        armor_destruction: 0.04,
        shield_bypass: 0.65,
        camo: true,
      },
    },
    {
      level: 3,
      price: 21000,
      stats: {
        damage: 68,
        crit_chance: 0.1,
        crit_dmg: 126,
        cooldown: 0.375,
        range: 180,
        targeting_rate: 0.6,
        radius: 7,
        burst: 10,
        burst_cd: 2,
        bleed: 3,
        armor_destruction: 0.04,
        shield_bypass: 0.75,
        camo: true,
      },
    },
    {
      level: 4,
      price: 102500,
      stats: {
        damage: 173,
        crit_chance: 0.12,
        crit_dmg: 153,
        cooldown: 0.325,
        range: 210,
        targeting_rate: 0.6,
        radius: 7,
        burst: 12,
        burst_cd: 2,
        bleed: 8,
        armor_destruction: 0.04,
        shield_bypass: 0.75,
        camo: true,
      },
    },
    {
      level: 5,
      price: 500000,
      stats: {
        damage: 525,
        crit_chance: 0.15,
        crit_dmg: 180,
        cooldown: 0.325,
        range: 210,
        targeting_rate: 0.75,
        radius: 8,
        burst: 12,
        burst_cd: 1.7,
        bleed: 18,
        armor_destruction: 0.04,
        shield_bypass: 0.85,
        camo: true,
      },
    },
    {
      level: 6,
      price: 2440000,
      stats: {
        damage: 1500,
        crit_chance: 0.15,
        crit_dmg: 225,
        cooldown: 0.25,
        range: 250,
        targeting_rate: 0.75,
        radius: 8,
        burst: 15,
        burst_cd: 1.7,
        bleed: 45,
        armor_destruction: 0.05,
        shield_bypass: 0.85,
        camo: true,
      },
    },
  ],
  paths: [
    {
      id: "a",
      level: 7,
      price: 40630000,
      stats: {
        damage: 9000,
        crit_chance: 0.15,
        crit_dmg: 540,
        cooldown: 0.25,
        range: 330,
        targeting_rate: 1,
        radius: 12,
        burst: 30,
        burst_cd: 1.7,
        bleed: 300,
        armor_destruction: 0.05,
        shield_bypass: 0.95,
        camo: true,
      },
    },
    {
      id: "b",
      level: 7,
      price: 46050000,
      stats: {
        damage: 4050,
        crit_chance: 0.28,
        crit_dmg: 225,
        cooldown: 0.09,
        range: 250,
        targeting_rate: 2.25,
        radius: 8,
        burst: 15,
        burst_cd: 0.5,
        bleed: 120,
        armor_destruction: 0.05,
        shield_bypass: 0.85,
        camo: true,
      },
    },
  ],
};
