//TODO: recheck stats
import { TowerRarity, TowerType, type Tower } from "../types";

export const quantum_turret: Tower = {
  id: "quantum_turret",
  name: "Quantum Turret",
  rarity: TowerRarity.Fabled,
  type: [TowerType.Offense],
  variantOf: "turret",
  levels: [
    {
      level: 1,
      price: 9100,
      stats: {
        damage: 18,
        crit_chance: 0.15,
        crit_dmg: 10,
        cooldown: 0.4,
        range: 750,
        exclusion: 100,
        targeting_rate: 0.7,
        radius: 1.5,
        bleed: 1,
        all_seeing: 3,
        shield_bypass: 1,
        armor_piercing: true,
        camo: true,
      },
    },
    {
      level: 2,
      price: 6200,
      stats: {
        damage: 25,
        crit_chance: 0.2,
        crit_dmg: 11.5,
        cooldown: 0.375,
        range: 900,
        exclusion: 100,
        targeting_rate: 0.7,
        radius: 1.5,
        bleed: 1,
        all_seeing: 3.3,
        shield_bypass: 1,
        armor_piercing: true,
        camo: true,
      },
    },
    {
      level: 3,
      price: 11_300,
      stats: {
        damage: 45,
        crit_chance: 0.2,
        crit_dmg: 14,
        cooldown: 0.375,
        range: 900,
        exclusion: 100,
        targeting_rate: 0.9,
        radius: 1.75,
        bleed: 2,
        all_seeing: 3.3,
        shield_bypass: 1,
        armor_piercing: true,
        camo: true,
      },
    },
    {
      level: 4,
      price: 55200,
      stats: {
        damage: 115,
        crit_chance: 0.25,
        crit_dmg: 17,
        cooldown: 0.325,
        range: 1050,
        exclusion: 100,
        targeting_rate: 0.9,
        radius: 1.75,
        bleed: 5,
        all_seeing: 3.8,
        shield_bypass: 1,
        armor_piercing: true,
        camo: true,
      },
    },
    {
      level: 5,
      price: 270000,
      stats: {
        damage: 350,
        crit_chance: 0.3,
        crit_dmg: 20,
        cooldown: 0.325,
        range: 1050,
        exclusion: 100,
        targeting_rate: 1.05,
        radius: 2,
        bleed: 12,
        all_seeing: 4.2,
        shield_bypass: 1,
        armor_piercing: true,
        camo: true,
      },
    },
    {
      level: 6,
      price: 1313400,
      stats: {
        damage: 1000,
        crit_chance: 0.3,
        crit_dmg: 25,
        cooldown: 0.25,
        range: 1250,
        exclusion: 100,
        targeting_rate: 1.05,
        radius: 2,
        bleed: 30,
        all_seeing: 5.3,
        shield_bypass: 1,
        armor_piercing: true,
        camo: true,
      },
    },
  ],
  paths: [
    {
      id: "a",
      level: 7,
      price: 21878500,
      stats: {
        damage: 6000,
        crit_chance: 0.3,
        crit_dmg: 60,
        cooldown: 0.25,
        range: 1650,
        exclusion: 100,
        targeting_rate: 1.4,
        radius: 3,
        bleed: 200,
        all_seeing: 5.3,
        shield_bypass: 1,
        armor_piercing: true,
        camo: true,
      },
    },
    {
      id: "b",
      level: 7,
      price: 24800000,
      stats: {
        damage: 2700,
        crit_chance: 0.55,
        crit_dmg: 25,
        cooldown: 0.09,
        range: 1250,
        exclusion: 100,
        targeting_rate: 3.15,
        radius: 2,
        bleed: 80,
        all_seeing: 7.8,
        shield_bypass: 1,
        armor_piercing: true,
        camo: true,
      },
    },
  ],
};
