// TODO: Add ability
import { TowerRarity, TowerType, type Tower } from "../types";

export const raygunner: Tower = {
  id: "raygunner",
  name: "Raygunner",
  rarity: TowerRarity.Prestigious,
  type: [TowerType.Offense],
  variantOf: "raygunner",
  levels: [
    {
      level: 1,
      price: 5100,
      stats: {
        damage: 32,
        damage_cap: 2000000,
        min_dmg_increase: 0.06,
        max_dmg_increase: 0.16,
        cooldown: 1.2,
        range: 85,
        shield_dmg: 3,
      },
    },
    {
      level: 2,
      price: 2400,
      stats: {
        damage: 32,
        damage_cap: 3500000,
        min_dmg_increase: 0.1,
        max_dmg_increase: 0.16,
        cooldown: 1.2,
        range: 95,
        shield_dmg: 3,
      },
    },
    {
      level: 3,
      price: 6300,
      stats: {
        damage: 64,
        damage_cap: 5500000,
        min_dmg_increase: 0.1,
        max_dmg_increase: 0.18,
        cooldown: 1.2,
        range: 100,
        shield_dmg: 3,
      },
    },
    {
      level: 4,
      price: 20300,
      stats: {
        damage: 256,
        damage_cap: 7500000,
        min_dmg_increase: 0.1,
        max_dmg_increase: 0.24,
        cooldown: 1.1,
        range: 100,
        shield_dmg: 3,
      },
    },
    {
      level: 5,
      price: 73600,
      stats: {
        damage: 512,
        damage_cap: 10000000,
        min_dmg_increase: 0.16,
        max_dmg_increase: 0.32,
        cooldown: 1.1,
        range: 100,
        shield_dmg: 3,
      },
    },
    {
      level: 6,
      price: 232900,
      stats: {
        damage: 2048,
        damage_cap: 10000000,
        min_dmg_increase: 0.16,
        max_dmg_increase: 0.32,
        cooldown: 1,
        range: 110,
        camo: true,
        shield_dmg: 3,
      },
    },
  ],
  paths: [
    {
      id: "a",
      level: 7,
      price: 1540000,
      stats: {
        damage: 16384,
        damage_cap: 12000000,
        min_dmg_increase: 1.28,
        max_dmg_increase: 2.48,
        cooldown: 1.65,
        range: 165,
        camo: true,
        shield_dmg: 3,
      },
    },
    {
      id: "b",
      level: 7,
      price: 1860000,
      stats: {
        damage: 2048,
        damage_cap: 10000000,
        min_dmg_increase: 0.16,
        max_dmg_increase: 0.32,
        cooldown: 0.5,
        range: 110,
        camo: true,
        shield_dmg: 3,
      },
    },
    {
      id: "c",
      level: 7,
      price: 2080000,
      stats: {
        damage: 8192,
        damage_cap: 15000000,
        min_dmg_increase: 0.64,
        max_dmg_increase: 0.96,
        cooldown: 1,
        range: 135,
        armor_piercing: true,
        camo: true,
        shield_dmg: 3,
        price: 2080000,
      },
    },
  ],
};
