// TODO: Check ability
import { TowerRarity, TowerType, type Tower } from "../types";

export const raygunner_alpha: Tower = {
  id: "raygunner_alpha",
  name: "Raygunner (Alpha)",
  type: [TowerType.Offense],
  rarity: TowerRarity.Lustrous,
  variantOf: "raygunner",
  levels: [
    {
      level: 1,
      price: 1550,
      stats: {
        damage: 8,
        damage_cap: 2000000,
        min_dmg_increase: 0.6,
        max_dmg_increase: 1.2,
        cooldown: 1.2,
        range: 85,
        shield_dmg: 3,
      },
    },
    {
      level: 2,
      price: 4750,
      stats: {
        damage: 20,
        damage_cap: 3000000,
        min_dmg_increase: 0.6,
        max_dmg_increase: 1.5,
        cooldown: 1.2,
        range: 100,
        shield_dmg: 3,
      },
    },
    {
      level: 3,
      price: 26200,
      stats: {
        damage: 90,
        damage_cap: 3000000,
        min_dmg_increase: 0.9,
        max_dmg_increase: 1.5,
        cooldown: 1.08,
        range: 100,
        camo: true,
        shield_dmg: 3,
      },
    },
    {
      level: 4,
      price: 144100,
      stats: {
        damage: 400,
        damage_cap: 6000000,
        min_dmg_increase: 0.9,
        max_dmg_increase: 2,
        cooldown: 1.08,
        range: 115,
        camo: true,
        shield_dmg: 3,
      },
    },
    {
      level: 5,
      price: 792200,
      stats: {
        damage: 2000,
        damage_cap: 15000000,
        min_dmg_increase: 0.9,
        max_dmg_increase: 2,
        cooldown: 0.84,
        range: 115,
        armor_piercing: true,
        camo: true,
        shield_dmg: 3,
      },
    },
    {
      level: 6,
      price: 4357000,
      stats: {
        damage: 9200,
        damage_cap: 45000000,
        min_dmg_increase: 1.25,
        max_dmg_increase: 2.75,
        cooldown: 0.84,
        range: 135,
        armor_piercing: true,
        camo: true,
        shield_dmg: 3,
      },
    },
  ],
  paths: [
    {
      id: "a",
      level: 7,
      price: 82783000,
      stats: {
        damage: 140000,
        damage_cap: 500000000,
        min_dmg_increase: 1.85,
        max_dmg_increase: 3.75,
        cooldown: 0.84,
        range: 135,
        armor_piercing: true,
        camo: true,
        shield_dmg: 3,
      },
    },
    {
      id: "b",
      level: 7,
      price: 95854000,
      stats: {
        damage: 27000,
        damage_cap: 45000000,
        min_dmg_increase: 1.25,
        max_dmg_increase: 1.5,
        cooldown: 0.5,
        range: 135,
        armor_piercing: true,
        camo: true,
        shield_dmg: 3,
      },
    },
    {
      id: "c",
      level: 7,
      price: 112193000,
      stats: {
        damage: 500000,
        damage_cap: 9999999999,
        min_dmg_increase: 1.25,
        max_dmg_increase: 7.77,
        cooldown: 4,
        range: 175,
        armor_piercing: true,
        camo: true,
        shield_dmg: 3,
      },
    },
  ],
};
