// TODO: recheck stats
import { TowerRarity, TowerType, type Tower } from "../types";

export const samurai_sentinel: Tower = {
  id: "samurai_sentinel",
  name: "Samurai Sentinel",
  type: [TowerType.Offense],
  rarity: TowerRarity.Legendary,
  levels: [
    {
      level: 1,
      price: 999,
      stats: {
        damage: 4,
        cooldown: 0.1,
        range: 25,
        radius: 4,
        purify: 3,
        armor_piercing: true,
        shield_dmg: 1,
      },
    },
    {
      level: 2,
      price: 1450,
      stats: {
        damage: 10,
        cooldown: 0.1,
        range: 25,
        radius: 4,
        purify: 2,
        armor_piercing: true,
        shield_dmg: 2,
      },
    },
    {
      level: 3,
      price: 2480,
      stats: {
        damage: 50,
        cooldown: 0.2,
        range: 25,
        radius: 8,
        purify: 2,
        armor_piercing: true,
        shield_dmg: 3,
      },
    },
    {
      level: 4,
      price: 4670,
      stats: {
        damage: 600,
        cooldown: 0.5,
        range: 25,
        radius: 8,
        purify: 4,
        armor_piercing: true,
        shield_dmg: 6,
      },
    },
    {
      level: 5,
      price: 12847,
      stats: {
        damage: 4563,
        cooldown: 1.5,
        range: 25,
        radius: 8,
        purify: 4,
        paralyze: 0.1,
        armor_piercing: true,
        camo: true,
        shield_dmg: 30,
      },
    },
    {
      level: 6,
      price: 45624,
      stats: {
        damage: 8975,
        cooldown: 2,
        range: 25,
        radius: 8,
        purify: 5,
        paralyze: 0.1,
        armor_piercing: true,
        camo: true,
        soul_damage: 0.2,
        shield_dmg: 45,
      },
    },
  ],
  paths: [
    {
      id: "a",
      level: 7,
      price: 3976315,
      stats: {
        damage: 56384,
        cooldown: 2,
        range: 40,
        radius: 8,
        purify: 5,
        paralyze: 0.2,
        shredding: 0.5,
        shredding_length: 4,
        execution: 4,
        armor_piercing: true,
        camo: true,
        soul_damage: 0.2,
        shield_dmg: 615,
      },
    },
    {
      id: "b",
      level: 7,
      price: 6354215,
      stats: {
        damage: 4532,
        cooldown: 0.05,
        crit_chance: 0.1,
        crit_dmg: 4,
        range: 25,
        radius: 8,
        purify: 10,
        paralyze: 0.1,
        valor: 2,
        armor_piercing: true,
        camo: true,
        soul_damage: 0.2,
        shield_dmg: 120,
      },
    },
  ],
};
