// TODO: check type
import { TowerRarity, TowerType, type Tower } from "../types";
export const shrine_of_apollo: Tower = {
  id: "shrine_of_apollo",
  name: "Shrine of Apollo",
  rarity: TowerRarity.Prestigious,
  type: [TowerType.Offense],
  variantOf: "shrine_of_apollo",
  levels: [
    {
      level: 1,
      price: 9_300,
      stats: {
        damage: 4,
        beams: 4,
        cooldown: 0.5,
        radius: 3,
        rad_strength: 0.02,
        rad_length: 1.5,
        armor_piercing: true,
        camo: true,
        shield_dmg: 0.5,
      },
    },
    {
      level: 2,
      price: 4_600,
      stats: {
        damage: 7,
        beams: 5,
        cooldown: 0.5,
        radius: 3,
        rad_strength: 0.02,
        rad_length: 2,
        armor_piercing: true,
        camo: true,
        shield_dmg: 0.5,
      },
    },
    {
      level: 3,
      price: 11_000,
      stats: {
        damage: 16,
        beams: 5,
        cooldown: 0.5,
        radius: 4,
        rad_strength: 0.03,
        rad_length: 2,
        armor_piercing: true,
        camo: true,
        shield_dmg: 0.5,
      },
    },
    {
      level: 4,
      price: 41_800,
      stats: {
        damage: 40,
        beams: 6,
        cooldown: 0.5,
        radius: 4,
        rad_strength: 0.03,
        rad_length: 2.5,
        armor_piercing: true,
        camo: true,
        shield_dmg: 0.5,
      },
    },
    {
      level: 5,
      price: 154_000,
      stats: {
        damage: 100,
        beams: 8,
        cooldown: 0.5,
        radius: 6,
        rad_strength: 0.05,
        rad_length: 2.5,
        armor_piercing: true,
        camo: true,
        shield_dmg: 0.5,
      },
    },
    {
      level: 6,
      price: 540_600,
      stats: {
        damage: 280,
        beams: 9,
        cooldown: 0.4,
        radius: 6,
        rad_strength: 0.05,
        rad_length: 3,
        armor_piercing: true,
        camo: true,
        shield_dmg: 0.5,
      },
    },
  ],
  paths: [
    {
      id: "a",
      level: 7,
      price: 4_890_000,
      stats: {
        damage: 1_000,
        beams: 9,
        cooldown: 0.4,
        radius: 9,
        rad_strength: 0.08,
        rad_length: 3,
        armor_piercing: true,
        camo: true,
        shield_dmg: 0.5,
      },
    },
    {
      id: "b",
      level: 7,
      price: 6_140_000,
      stats: {
        damage: 800,
        beams: 12,
        cooldown: 0.35,
        radius: 6,
        rad_strength: 0.05,
        rad_length: 4.5,
        execution: 1.35,
        armor_piercing: true,
        camo: true,
        shield_dmg: 0.5,
      },
    },
  ],
};
