import { type Tower } from "../types";

export const stryker: Tower = [
  {
    damage: 75,
    cooldown: 15,
    exclusion: 80,
    radius: 65,
    inaccuracy: 60,
    rad_strength: 0.4,
    rad_length: 4,
    armor_piercing: true,
    camo: true,
    price: 6400,
  },
  {
    damage: 75,
    cooldown: 12,
    exclusion: 70,
    radius: 65,
    inaccuracy: 60,
    rad_strength: 0.4,
    rad_length: 4,
    armor_piercing: true,
    camo: true,
    price: 2000,
  },
  {
    damage: 125,
    cooldown: 12,
    exclusion: 70,
    radius: 75,
    inaccuracy: 55,
    rad_strength: 0.4,
    rad_length: 5,
    armor_piercing: true,
    camo: true,
    price: 7500,
  },
  {
    damage: 225,
    cooldown: 10,
    exclusion: 60,
    radius: 75,
    inaccuracy: 50,
    rad_strength: 0.6,
    rad_length: 5,
    armor_piercing: true,
    camo: true,
    price: 25000,
  },
  {
    damage: 600,
    cooldown: 10,
    exclusion: 60,
    radius: 85,
    inaccuracy: 50,
    rad_strength: 0.6,
    rad_length: 5.5,
    armor_piercing: true,
    camo: true,
    price: 80000,
  },
  {
    damage: 1500,
    cooldown: 10,
    exclusion: 60,
    radius: 85,
    inaccuracy: 40,
    rad_strength: 0.9,
    rad_length: 5.5,
    armor_piercing: true,
    camo: true,
    price: 250000,
  },
  {
    damage: 5000,
    cooldown: 10,
    exclusion: 60,
    radius: 100,
    inaccuracy: 40,
    rad_strength: 0.9,
    rad_length: 7,
    armor_piercing: true,
    camo: true,
    price: 1550000,
  },
  {
    damage: 5000,
    cooldown: 8.5,
    exclusion: 30,
    radius: 85,
    inaccuracy: 25,
    rad_strength: 1.2,
    rad_length: 5.5,
    armor_piercing: true,
    camo: true,
    price: 2000000,
  },
];
