import { TowerRarity, TowerType, type Tower } from "../types";

export const summer_stryker: Tower = {
  id: "summer_stryker",
  name: "Summer Stryker",
  rarity: TowerRarity.Illustrious,
  type: [TowerType.Support],
  variantOf: "stryker",
  levels: [
    {
      level: 1,
      price: 24353,
      stats: {
        damage: 75,
        cooldown: 5,
        exclusion: 200,
        radius: 65,
        inaccuracy: 1,
        residue_length: 12,
        scorch: 0.0125,
        scorch_length: 12,
        rad_strength: 1.2,
        rad_length: 4,
        armor_piercing: true,
        camo: true,
      },
    },
    {
      level: 2,
      price: 200000,
      stats: {
        damage: 75,
        cooldown: 2.5,
        exclusion: 200,
        radius: 65,
        inaccuracy: 1,
        residue_length: 12,
        scorch: 0.0125,
        scorch_length: 12,
        rad_strength: 1.2,
        rad_length: 4,
        armor_piercing: true,
        camo: true,
      },
    },
    {
      level: 3,
      price: 750000,
      stats: {
        damage: 75,
        cooldown: 2.5,
        exclusion: 200,
        radius: 125,
        inaccuracy: 1,
        residue_length: 12,
        scorch: 0.0125,
        scorch_length: 12,
        rad_strength: 1.2,
        rad_length: 8,
        armor_piercing: true,
        camo: true,
      },
    },
    {
      level: 4,
      price: 2500000,
      stats: {
        damage: 225,
        cooldown: 10,
        exclusion: 60,
        radius: 125,
        inaccuracy: 1,
        residue_length: 12,
        scorch: 0.0125,
        scorch_length: 12,
        rad_strength: 0.6,
        rad_length: 8,
        armor_piercing: true,
        camo: true,
      },
    },
    {
      level: 5,
      price: 8000000,
      stats: {
        damage: 225,
        cooldown: 10,
        exclusion: 60,
        radius: 125,
        inaccuracy: 1,
        residue_length: 14,
        scorch: 0.015,
        scorch_length: 14,
        rad_strength: 0.6,
        rad_length: 16,
        armor_piercing: true,
        camo: true,
      },
    },
    {
      level: 6,
      price: 25000000,
      stats: {
        damage: 225,
        cooldown: 10,
        exclusion: 60,
        radius: 125,
        inaccuracy: 1,
        residue_length: 14,
        scorch: 0.015,
        scorch_length: 14,
        rad_strength: 1.5,
        rad_length: 16,
        armor_piercing: true,
        camo: true,
      },
    },
  ],
  paths: [
    {
      id: "a",
      level: 7,
      price: 155000000,
      stats: {
        damage: 5000000000,
        cooldown: 10,
        exclusion: 300,
        radius: 125,
        inaccuracy: 1,
        residue_length: 14,
        scorch: 0.015,
        scorch_length: 14,
        rad_strength: 1.5,
        rad_length: 16,
        armor_piercing: true,
        camo: true,
      },
    },
    {
      id: "b",
      level: 7,
      price: 200000000,
      stats: {
        damage: 225,
        cooldown: 5,
        exclusion: 300,
        radius: 125,
        inaccuracy: 1,
        residue_length: 14,
        scorch: 0.015,
        scorch_length: 14,
        rad_strength: 2,
        rad_length: 16,
        armor_piercing: true,
        camo: true,
      },
    },
  ],
};
