// TODO: check stats
import { TowerRarity, TowerType, type Tower } from "../types";

export const super_stryker: Tower = {
  id: "super_stryker",
  name: "Super Stryker",
  variantOf: "stryker",
  type: [TowerType.Support],
  rarity: TowerRarity.Exalted,
  levels: [
    {
      level: 1,
      price: 8200,
      stats: {
        damage: 100,
        cooldown: 10,
        exclusion: 150,
        radius: 75,
        inaccuracy: 60,
        rad_strength: 0.5,
        rad_length: 5,
        armor_destruction: 0.1,
        camo: true,
      },
    },
    {
      level: 2,
      price: 3700,
      stats: {
        damage: 100,
        cooldown: 8.5,
        exclusion: 140,
        radius: 75,
        inaccuracy: 60,
        rad_strength: 0.5,
        rad_length: 5,
        armor_destruction: 0.15,
        camo: true,
      },
    },
    {
      level: 3,
      price: 9700,
      stats: {
        damage: 175,
        cooldown: 8.5,
        exclusion: 140,
        radius: 85,
        inaccuracy: 55,
        rad_strength: 0.5,
        rad_length: 6,
        armor_destruction: 0.15,
        camo: true,
      },
    },
    {
      level: 4,
      price: 36200,
      stats: {
        damage: 375,
        cooldown: 7.5,
        exclusion: 130,
        radius: 85,
        inaccuracy: 50,
        rad_strength: 0.65,
        rad_length: 6,
        armor_destruction: 0.15,
        camo: true,
      },
    },
    {
      level: 5,
      price: 128000,
      stats: {
        damage: 1000,
        cooldown: 7.5,
        exclusion: 130,
        radius: 95,
        inaccuracy: 50,
        rad_strength: 0.65,
        rad_length: 6.5,
        armor_destruction: 0.2,
        camo: true,
      },
    },
    {
      level: 6,
      price: 416000,
      stats: {
        damage: 2500,
        cooldown: 7,
        exclusion: 130,
        radius: 95,
        inaccuracy: 40,
        rad_strength: 1,
        rad_length: 6.5,
        armor_destruction: 0.2,
        camo: true,
        price: 416000,
      },
    },
  ],
  paths: [
    {
      id: "a",
      level: 7,
      price: 5420000,
      stats: {
        damage: 17500,
        cooldown: 7,
        exclusion: 130,
        radius: 120,
        inaccuracy: 40,
        rad_strength: 1,
        rad_length: 9,
        armor_destruction: 0.35,
        camo: true,
      },
    },
    {
      id: "b",
      level: 7,
      price: 6170000,
      stats: {
        damage: 7500,
        cooldown: 5.5,
        exclusion: 115,
        radius: 95,
        inaccuracy: 25,
        rad_strength: 1.5,
        rad_length: 6.5,
        armor_destruction: 0.2,
        camo: true,
      },
    },
  ],
};
