// TODO: check stats
import { TowerRarity, TowerType, type Tower } from "../types";

export const true_vaporizer: Tower = {
  id: "true_vaporizer",
  name: "True Vaporizer",
  rarity: TowerRarity.Exalted,
  type: [TowerType.Offense], // possibly +support?
  variantOf: "vaporizer",
  levels: [
    {
      level: 1,
      price: 4600,
      stats: {
        damage: 4,
        damage_increase: 3,
        cooldown: 0.5,
        max_cooldown: 1.8,
        min_cooldown: 0.5,
        acceleration: 0.12,
        range: 90,
        stun: 0.5,
        armor_destruction: 0.45,
        shield_dmg: 8,
      },
    },
    {
      level: 2,
      price: 2200,
      stats: {
        damage: 4,
        damage_increase: 3,
        cooldown: 0.5,
        max_cooldown: 1.6,
        min_cooldown: 0.5,
        acceleration: 0.12,
        range: 110,
        stun: 1,
        armor_destruction: 0.45,
        camo: true,
        shield_dmg: 8,
      },
    },
    {
      level: 3,
      price: 5200,
      stats: {
        damage: 15,
        damage_increase: 8,
        cooldown: 0.5,
        max_cooldown: 1.6,
        min_cooldown: 0.5,
        acceleration: 0.15,
        range: 120,
        stun: 1,
        armor_destruction: 0.55,
        camo: true,
        shield_dmg: 8,
      },
    },
    {
      level: 4,
      price: 19400,
      stats: {
        damage: 30,
        damage_increase: 23,
        cooldown: 0.425,
        max_cooldown: 1.6,
        min_cooldown: 0.425,
        acceleration: 0.15,
        range: 120,
        stun: 1,
        armor_destruction: 0.65,
        camo: true,
        shield_dmg: 8,
      },
    },
    {
      level: 5,
      price: 68400,
      stats: {
        damage: 100,
        damage_increase: 75,
        cooldown: 0.425,
        max_cooldown: 1.6,
        min_cooldown: 0.425,
        acceleration: 0.15,
        range: 145,
        stun: 1,
        armor_destruction: 0.65,
        camo: true,
        shield_dmg: 8,
      },
    },
    {
      level: 6,
      price: 256000,
      stats: {
        damage: 300,
        damage_increase: 225,
        cooldown: 0.335,
        max_cooldown: 1.6,
        min_cooldown: 0.335,
        acceleration: 0.18,
        range: 145,
        stun: 1,
        armor_destruction: 0.75,
        camo: true,
        shield_dmg: 8,
      },
    },
  ],
  paths: [
    {
      id: "a",
      level: 7,
      price: 3620000,
      stats: {
        damage: 40000,
        damage_increase: 30000,
        cooldown: 1.2,
        max_cooldown: 1.6,
        min_cooldown: 1.2,
        acceleration: 0.3,
        range: 210,
        stun: 2,
        armor_destruction: 0.75,
        camo: true,
        shield_dmg: 8,
      },
    },
    {
      id: "b",
      level: 7,
      price: 4127000,
      stats: {
        damage: 600,
        damage_increase: 450,
        cooldown: 0.05,
        max_cooldown: 0.01,
        min_cooldown: 0.05,
        acceleration: 0.18,
        range: 145,
        stun: 1,
        armor_destruction: 0.75,
        camo: true,
        shield_dmg: 8,
      },
    },
  ],
};
