import { TowerRarity, TowerType, type Tower } from "../types";

export const zero_two: Tower = {
  id: "zero_two",
  name: "Zero Two",
  rarity: TowerRarity.Prestigious,
  type: [TowerType.Offense],
  variantOf: "zero_two",
  levels: [
    {
      level: 1,
      price: 3800,
      stats: {
        damage: 2,
        cooldown: 0.18,
        range: 65,
        bleed: 1,
        hollow_point: 1.5,
        execution: 1.2,
        shield_dmg: 0.3,
      },
    },
    {
      level: 2,
      price: 1700,
      stats: {
        damage: 3,
        cooldown: 0.18,
        range: 75,
        bleed: 2,
        hollow_point: 2,
        execution: 1.2,
        shield_dmg: 0.3,
      },
    },
    {
      level: 3,
      price: 4600,
      stats: {
        damage: 6,
        cooldown: 0.18,
        range: 80,
        bleed: 3,
        hollow_point: 2,
        execution: 1.5,
        shield_dmg: 0.3,
      },
    },
    {
      level: 4,
      price: 21700,
      stats: {
        damage: 15,
        cooldown: 0.18,
        range: 80,
        bleed: 6,
        hollow_point: 3.5,
        execution: 1.5,
        shield_dmg: 0.3,
      },
    },
    {
      level: 5,
      price: 78500,
      stats: {
        damage: 40,
        cooldown: 0.15,
        range: 95,
        bleed: 13,
        hollow_point: 3.5,
        execution: 1.9,
        shield_dmg: 0.3,
      },
    },
    {
      level: 6,
      price: 294000,
      stats: {
        damage: 100,
        cooldown: 0.15,
        range: 110,
        bleed: 30,
        hollow_point: 3.5,
        execution: 2.7,
        camo: true,
        shield_dmg: 0.3,
      },
    },
  ],
  paths: [
    {
      id: "a",
      level: 7,
      price: 2002002,
      stats: {
        damage: 750,
        cooldown: 0.15,
        range: 110,
        bleed: 90,
        hollow_point: 3.5,
        execution: 10,
        camo: true,
        shield_dmg: 0.3,
      },
    },
    {
      id: "b",
      level: 7,
      price: 3002002,
      stats: {
        damage: 100,
        cooldown: 0.09,
        range: 135,
        bleed: 200,
        hollow_point: 5,
        execution: 2.7,
        camo: true,
        shield_dmg: 0.3,
      },
    },
  ],
};
